In [1]:
%run utils/dataset_tools.ipynb
%run utils/network_tools.ipynb
%run utils/training_tools.ipynb

In [2]:
# Notes for saving and loading Pytorch Models, from 
# https://pytorch.org/tutorials/beginner/saving_loading_models.html
'''
model = TheModelClass(*args, **kwargs)
optimizer = TheOptimizerClass(*args, **kwargs)

checkpoint = torch.load(PATH)
model.load_state_dict(checkpoint['model_state_dict'])
optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
epoch = checkpoint['epoch']
loss = checkpoint['loss']

model.eval()
# - or -
model.train()
'''
# Useful reference for saving off weights, etc, that we might need and/or want

"\nmodel = TheModelClass(*args, **kwargs)\noptimizer = TheOptimizerClass(*args, **kwargs)\n\ncheckpoint = torch.load(PATH)\nmodel.load_state_dict(checkpoint['model_state_dict'])\noptimizer.load_state_dict(checkpoint['optimizer_state_dict'])\nepoch = checkpoint['epoch']\nloss = checkpoint['loss']\n\nmodel.eval()\n# - or -\nmodel.train()\n"

In [3]:
model_pent = MagNet()
opt_pent = torch.optim.Adam(model_pent.parameters(), lr=learning_rate)
check_pent = torch.load('SavedModels/Velocity/N2_G5_Loocv4_best.tar')
model_pent.load_state_dict(check_pent['model_state_dict'])
opt_pent.load_state_dict(check_pent['optimizer_state_dict'])
epoch_pent = check_pent['epoch']
loss_pent = check_pent['loss']

model_hex = MagNet()
opt_hex = torch.optim.Adam(model_hex.parameters(), lr=learning_rate)
check_hex = torch.load('SavedModels/Velocity/N2_G6_Loocv4_best.tar')
model_hex.load_state_dict(check_hex['model_state_dict'])
opt_hex.load_state_dict(check_hex['optimizer_state_dict'])
epoch_hex = check_hex['epoch']
loss_hex = check_hex['loss']

In [4]:
model_pent.eval()
print(model_pent)

print()

model_hex.eval()
print(model_hex)

MagNet(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=3, out_features=6, bias=True)
    (1): Tanh()
    (2): Linear(in_features=6, out_features=1, bias=True)
  )
)

MagNet(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=3, out_features=6, bias=True)
    (1): Tanh()
    (2): Linear(in_features=6, out_features=1, bias=True)
  )
)


In [5]:
print(model_pent(torch.zeros(1, 3)))
print()
print(model_pent(0.01*torch.ones(1, 3)))

tensor([[0.4633]], grad_fn=<AddmmBackward0>)

tensor([[0.5395]], grad_fn=<AddmmBackward0>)


In [6]:
print(model_hex(torch.zeros(1, 3)))
print()
print(model_hex(0.01*torch.ones(1, 3)))

tensor([[-0.1452]], grad_fn=<AddmmBackward0>)

tensor([[-0.0139]], grad_fn=<AddmmBackward0>)
